spring:
  jackson:
    default-property-inclusion: non_null
  main:
    allow-circular-references: true
  application:
    name: student-manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student-manager?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 111111

# application.yml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
